# Generated by Django 3.2.5 on 2021-07-22 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='default_default_country',
            new_name='default_country',
        ),
    ]
